### PR TITLE
This commit changes 4 colors in the tailwind config file:

### PR DESCRIPTION
**Pull request by Gitstar-OC**
- Background color is changed to white (1 0 0)
- Border color is changed to shade of a blue (60% 0.09 235.71) 
- Changed the color of display card from shade of blue to shade of white (95% 0 0) 
- Changed the color of the selector to a more lighter shade.

This pr will make the light theme ui better.

### CODE REVIEW

**Comment by Gitstar-OC** [comment]
Hey please note that there are also additional things that will be changed with an upcoming pr

- There is a purple color for own profile in the leaderboard if the theme is dark but there is nothing similar for light theme. 
- There are three colors for accent (purple for hovering, blue and orange ) which after the pr is merged will be 2 ( purple for hovering and blue as accent ) which will be changed in the same upcoming pr and 2 accent colors will be red and blue. 

- The colors are graphs and charts are currently green and will be changed to shades of red in the upcoming pr. 

**I was unable to submit it because of some issues while running the docker and will shortly do a pr.**

**Comment by Gitstar-OC** [comment]
image

**Like this**

**Comment by Gitstar-OC** [comment]
Will pull another pr today (in 12 to 15 hours from now!!)

**Comment by Gitstar-OC** [comment]
Merge this one, will push the changes after this is merged and active to see what other changes can be done!

**Comment by taciturnaxolotl** [comment]
I don't think this currently fits the theme I'm going for right now

image

**Comment by Gitstar-OC** [comment]
Oh, yes sorry you should not, I did not check that the text color beside the chart is still a shade of white and not black. Will create a pr with all of the remaining changes today. Thanks!

**Pull request merged**
