### PR TITLE
CONFIDENTIAL: Far Shores event name update

### PR DESCRIPTION
**Pull request by TheScientist101**
Hey Kieran,

It's getting late, but I thought I should change the event name to match Far Shores before we announce it tomorrow. Can you confirm that this PR is private? I tried to follow a tutorial online, but I'm not sure if it worked.

This should've been pretty basic, but I'm tired, so lmk if I made any mistakes.

Thanks,
Urjith Mishra
Hack Club Far Shores Team Member

### CODE REVIEW

**Comment by taciturnaxolotl** [comment]
i think you mixed up the name in the code lol; it should be `far shores` instead of `high seas` :)

**Comment by taciturnaxolotl** [comment]
thanks for keeping this confidential

**Comment by TheScientist101** [comment]
Oops, it's getting late here. I'll fix it in the morning before launch. I think the leeks trolls are getting to me lol

**Comment by Bee4Queer** [comment]
Just so you know, there's no such thing as a private PR.

**Comment by fishtested** [comment]
Reminder: All PRs are public 👀

**Comment by opticaldrive** [comment]
This was not confidential whahaha

**Pull request merged**
